# Generated by Django 5.0.14 on 2025-10-05 14:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_alter_heroslider_image'),
        ('users', '0007_jobapplication_alternative_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the person requesting quote', max_length=100)),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('destination', models.CharField(help_text='Preferred destination or region', max_length=100)),
                ('preferred_travel_dates', models.CharField(help_text='Preferred travel dates (flexible dates welcome)', max_length=200)),
                ('number_of_travelers', models.PositiveIntegerField(default=1, help_text='Number of people traveling')),
                ('special_requests', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Any special requirements, preferences, or additional information', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the quote request was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_email_sent', models.BooleanField(default=False, help_text='Whether confirmation email was sent to user')),
                ('admin_notification_sent', models.BooleanField(default=False, help_text='Whether notification was sent to admin')),
                ('status', models.CharField(choices=[('new', 'New Request'), ('contacted', 'Contacted'), ('quoted', 'Quote Sent'), ('confirmed', 'Booking Confirmed'), ('cancelled', 'Cancelled')], default='new', help_text='Current status of the quote request', max_length=20)),
                ('package', models.ForeignKey(blank=True, help_text='Specific package if requesting quote for existing package', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminside.package')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
