# Generated by Django 5.0.14 on 2026-09-27 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_quoterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('follow_up_type', models.CharField(choices=[('booking', 'Booking'), ('quote', 'Quote Request'), ('mice', 'MICE Inquiry'), ('student', 'Student Travel'), ('ngo', 'NGO Travel'), ('job', 'Job Application'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='users.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='users.jobapplication')),
                ('mice_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='users.miceinquiry')),
                ('ngo_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='users.ngotravelinquiry')),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='users.quoterequest')),
                ('student_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='users.studenttravelinquiry')),
            ],
            options={
                'ordering': ['status', 'due_at', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='users_follo_status_95a4aa_idx'), models.Index(fields=['follow_up_type', 'status'], name='users_follo_follow__c624dc_idx'), models.Index(fields=['assigned_to', 'status'], name='users_follo_assigne_f8e850_idx'), models.Index(fields=['priority', 'due_at'], name='users_follo_priorit_467b29_idx')],
            },
        ),
    ]
