# Generated by Django 5.0.14 on 2026-09-30 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_make_package_image_optional'),
        ('users', '0009_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('destination_or_trip', models.CharField(blank=True, max_length=180)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('feedback', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='What went especially well?')),
                ('improvements', models.TextField(blank=True, help_text='What could Myriad improve?')),
                ('permission_to_publish', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_visible_on_site', models.BooleanField(default=False, help_text='Show this feedback on public review sections.')),
                ('is_featured', models.BooleanField(default=False, help_text='Prioritize this feedback in public review sections.')),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_feedback', to='users.booking')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_feedback', to='adminside.package')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trip_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Feedback',
                'verbose_name_plural': 'Trip Feedback',
                'ordering': ['-is_featured', '-submitted_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_tripf_status_3a9473_idx'), models.Index(fields=['is_visible_on_site', 'is_featured'], name='users_tripf_is_visi_3d99ca_idx'), models.Index(fields=['token'], name='users_tripf_token_1ca63f_idx')],
            },
        ),
    ]
