# Generated by Django 5.0.14 on 2026-10-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tripfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='citizenship',
            field=models.CharField(blank=True, help_text='Citizenship or passport country for travel planning', max_length=100),
        ),
    ]
