# Generated by Django 5.0.14 on 2025-08-18 18:07

import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_alter_destination_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional caption/title for the hero slide', max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the hero slide', max_length=300, null=True)),
                ('image', pyuploadcare.dj.models.ImageField(help_text='Hero slider image (recommended size: 1920x1080px)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this slide')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance (lower numbers appear first)')),
                ('cta_text', models.CharField(blank=True, help_text="Call-to-action button text (e.g., 'Book Now', 'Explore')", max_length=50, null=True)),
                ('cta_url', models.URLField(blank=True, help_text='URL for the call-to-action button', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
