# Generated by Django 5.0.14 on 2025-08-27 21:55

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_populate_default_hero_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=pyuploadcare.dj.models.ImageField(help_text='Hero slider image (recommended size: 2048x1080px for optimal quality)'),
        ),
    ]
