# Generated by Django 5.0.14 on 2025-10-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_alter_heroslider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package Category',
                'verbose_name_plural': 'Package Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='adminside_p_slug_b82487_idx'), models.Index(fields=['is_active'], name='adminside_p_is_acti_50ed47_idx')],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Package category (e.g., Nairobi Excursions, Kenya Safaris, Outbound)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='adminside.packagecategory'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category', 'status'], name='adminside_p_categor_f6718a_idx'),
        ),
    ]
