# Generated by Django 5.0.14 on 2026-09-24 18:20

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_package_myriad_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='featured_image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
