# Generated by Django 5.0.14 on 2026-09-30 15:42

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_make_package_image_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='featured_image',
            field=pyuploadcare.dj.models.ImageField(blank=True, help_text='Package image. Uploadcare crop options include square, card, hero and poster ratios.', null=True),
        ),
    ]
