# Generated by Django 5.0.14 on 2026-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_alter_package_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['home_rank', '-is_featured', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='package',
            name='home_rank',
            field=models.PositiveIntegerField(default=100, help_text='Homepage selling order. Lower numbers appear first in the homepage package showcase.'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status', 'home_rank'], name='adminside_p_status_2495f5_idx'),
        ),
    ]
