# Generated by Django 5.0.14 on 2026-09-30 19:34

import django.db.models.deletion
import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0013_alter_package_options_package_home_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pyuploadcare.dj.models.ImageField(help_text='Gallery image. Use landscape for wide trip scenes or portrait for poster-style moments.')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('caption', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('captured_at', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='adminside.package')),
            ],
            options={
                'verbose_name': 'Package Gallery Image',
                'verbose_name_plural': 'Package Gallery Images',
                'ordering': ['display_order', '-captured_at', '-created_at'],
                'indexes': [models.Index(fields=['package', 'is_visible', 'display_order'], name='adminside_p_package_cc15ea_idx'), models.Index(fields=['package', 'captured_at'], name='adminside_p_package_aee964_idx')],
            },
        ),
    ]
