# Generated by Django 5.0.14 on 2026-10-07 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_packagegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('starts_on', models.DateField(help_text='First day to display this campaign.')),
                ('ends_on', models.DateField(help_text='Last day to display this campaign.')),
                ('travel_dates', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='adminside.package')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TravelCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('section', models.CharField(choices=[('kenya', 'Explore Kenya'), ('world', 'Explore The World'), ('safaris', 'Tours & Safaris'), ('themes', 'Themed Packages')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_navigation', models.BooleanField(default=True)),
                ('packages', models.ManyToManyField(blank=True, related_name='collections', to='adminside.package')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('ends_on__gte', models.F('starts_on'))), name='campaign_dates_in_order'),
        ),
    ]
