# Generated by Django 5.0.14 on 2026-10-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_campaign_travelcollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(blank=True, choices=[('kenya', 'Kenya'), ('africa', 'Africa'), ('americas', 'Americas'), ('asia', 'Asia'), ('australasia', 'Australasia'), ('europe', 'Europe'), ('indian-ocean-islands', 'Indian Ocean Islands'), ('middle-east', 'Middle East')], help_text='Used to place this destination in public navigation.', max_length=32),
        ),
    ]
