# Generated by Django 5.0.14 on 2026-10-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0016_destination_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagegalleryimage',
            options={'ordering': ['display_order', '-captured_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='destination',
            name='show_in_navigation',
            field=models.BooleanField(default=True, help_text='Allow this destination to appear in public navigation after it has a published package.'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='show_in_navigation',
            field=models.BooleanField(default=True, help_text='Show this category in relevant public navigation menus.'),
        ),
    ]
