# Generated by Django 5.0.14 on 2026-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_alter_packagegalleryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Additional public categories. The primary category remains the main card label.', related_name='tagged_packages', to='adminside.packagecategory'),
        ),
    ]
